# **Código de Limpieza de Datos - Proyecto de Grado 2025-1**
## **Identificación de contratos públicos sujetos a adiciones en el sector de la salud con modelos de machine learning**

### **Elaborado por:**  
#### Marco Antonio Cruz y Paula Andrea Ovalle
m.cruzg@uniandes.edu.co-202020941 y P.ovallev@uniandes.edu.co-202021735

## Librerias y carga csv

In [24]:
import pandas as pd
#from sklearn.ensemble import RandomForestClassifier
#from sklearn.preprocessing import LabelEncoder
#from xgboost import XGBClassifier
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [25]:
#### Activar segun quien trabaje 
#Marco
Filepath = "C:/Users/asus/OneDrive/Documentos/semestres uniandes/Clases 2025-1/Tesis IIND/Solo sector salud/Base final.csv"
#Paula
#Filepath=
df=pd.read_csv(Filepath)
df

C:\Users\asus\AppData\Local\Temp\ipykernel_4428\280836423.py:6: DtypeWarning: Columns (71) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(Filepath)

,nombre entidad,nit entidad,departamento,ciudad,localización,orden,sector,rama,entidad centralizada,proceso de compra,...,departamento proveedor,ciudad proveedor,fecha adjudicacion,valor total adjudicacion,nombre del adjudicador,nombre del proveedor adjudicado,estado de apertura del proceso,subtipo de contrato,estado resumen,Adicion
0,UESVALLE,805018833,Valle del Cauca,Cali,Colombia Valle del Cauca Cali,Territorial,Salud y Protección Social,Ejecutivo,Centralizada,CO1.BDOS.3116030,...,Valle del Cauca,Florida,NaN,0,No Adjudicado,ALVARO JAVIER TIGREROS HURTADO,Abierto,No Definido,Adjudicado,1
1,SUBRED INTEGRADA DE SERVICIOS DE SALUD NORTE E...,900971006,Distrito Capital de Bogotá,No Definido,Colombia Bogotá No Definido,Territorial,Salud y Protección Social,Corporación Autónoma,Descentralizada,CO1.BDOS.2328666,...,Distrito Capital de Bogotá,Bogotá,NaN,0,No Adjudicado,Camilo Alonso Peralta,Abierto,No Definido,Adjudicado,1
2,SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR OCC...,900959048,Distrito Capital de Bogotá,No Definido,Colombia Bogotá No Definido,Territorial,Salud y Protección Social,Ejecutivo,Descentralizada,CO1.BDOS.7179284,...,Distrito Capital de Bogotá,No Definido,NaN,0,No Adjudicado,FABIOLA VANEGAS PORRAS,Abierto,No Definido,Adjudicado,1
3,UNIDAD PRESTADORA DE SALUD ATLANTICO,9013620904,Atlántico,Soledad,Colombia Atlántico Soledad,Territorial,Salud y Protección Social,Ejecutivo,Descentralizada,CO1.BDOS.5872894,...,Atlántico,Barranquilla,04/16/2024,54000000,TATIANA CATALAN RIPOLL,ANDRES FELIPE MANJARRES MOLINA,Cerrado,No Definido,Adjudicado,1
4,SUBRED INTEGRADA DE SERVICIOS DE SALUD NORTE E...,900971006,Distrito Capital de Bogotá,No Definido,Colombia Bogotá No Definido,Territorial,Salud y Protección Social,Corporación Autónoma,Descentralizada,CO1.BDOS.414925,...,Distrito Capital de Bogotá,No Definido,NaN,0,No Adjudicado,Andrea Carolina Noches Buelvas,Abierto,No Definido,Adjudicado,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594512,RED SALUD CASANARE E.S.E. *,8440041972,Casanare,Yopal,Colombia Casanare Yopal,Territorial,Salud y Protección Social,Ejecutivo,Descentralizada,CO1.BDOS.5079011,...,Casanare,Villanueva,NaN,0,No Adjudicado,lida Marcela martinez,Abierto,No Definido,Adjudicado,0
594513,SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR OCC...,900959048,Distrito Capital de Bogotá,No Definido,Colombia Bogotá No Definido,Territorial,Salud y Protección Social,Ejecutivo,Descentralizada,CO1.BDOS.1053876,...,Cundinamarca,No Definido,NaN,0,No Adjudicado,YAMILY CIRO MARIN,Abierto,No Definido,Adjudicado,1
594514,ICBF REGIONAL NARIÑO,899999239,Nariño,No Definido,Colombia Nariño No Definido,Nacional,Salud y Protección Social,Ejecutivo,Centralizada,CO1.BDOS.6359883,...,Nariño,Pasto,NaN,0,No Adjudicado,HUMBERTO JAVIER PALACIOS ORDOÑEZ,Abierto,No Definido,Adjudicado,0
594515,SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR OCC...,900959048,Distrito Capital de Bogotá,No Definido,Colombia Bogotá No Definido,Territorial,Salud y Protección Social,Ejecutivo,Descentralizada,CO1.BDOS.7401171,...,Distrito Capital de Bogotá,Bogotá,NaN,0,No Adjudicado,WILLIAM DAVID ARREGOCES FERNANDEZ,Abierto,No Definido,Adjudicado,0
594516,SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR OCC...,900959048,Distrito Capital de Bogotá,No Definido,Colombia Bogotá No Definido,Territorial,Salud y Protección Social,Ejecutivo,Descentralizada,CO1.BDOS.1053876,...,Cundinamarca,No Definido,NaN,0,No Adjudicado,YAMILY CIRO MARIN,Abierto,No Definido,Adjudicado,1

In [26]:
print(list(df.columns))

['nombre entidad', 'nit entidad', 'departamento', 'ciudad', 'localización', 'orden', 'sector', 'rama', 'entidad centralizada', 'proceso de compra', 'id contrato', 'estado contrato', 'codigo de categoria principal', 'tipo de contrato', 'modalidad de contratacion', 'justificacion modalidad de contratacion', 'fecha de firma', 'fecha de inicio del contrato', 'fecha de fin del contrato', 'fecha de inicio de ejecucion', 'fecha de fin de ejecucion', 'condiciones de entrega', 'es grupo', 'es pyme', 'habilita pago adelantado', 'liquidación', 'obligación ambiental', 'obligaciones postconsumo', 'reversion', 'origen de los recursos', 'destino gasto', 'valor del contrato', 'valor de pago adelantado', 'valor facturado', 'valor pendiente de pago', 'valor pagado', 'valor amortizado', 'valor pendiente de amortizacion', 'valor pendiente de ejecucion', 'estado bpin', 'código bpin', 'anno bpin', 'saldo cdp', 'saldo vigencia', 'espostconflicto', 'dias adicionados', 'puntos del acuerdo', 'pilares del acuerdo', 'nombre representante legal', 'nacionalidad representante legal', 'presupuesto general de la nacion – pgn', 'sistema general de participaciones', 'sistema general de regalías', 'recursos propios (alcaldias_gobernaciones_resguardosindigenas)', 'recursos de credito', 'recursos propios', 'ultima actualizacion', 'codigo entidad', 'fecha inicio liquidacion', 'fecha fin liquidacion', 'duración del contrato', 'el contrato puede ser prorrogado', 'fecha de notificación de prorrogación', 'nombre ordenador del gasto', 'nombre supervisor', 'nombre ordenador de pago', 'id del proceso', 'id del portafolio', 'fase', 'fecha de publicacion del proceso', 'fecha de ultima publicación', 'fecha de publicacion (manifestacion de interes)', 'fecha de publicacion (fase borrador)', 'fecha de publicacion (fase seleccion)', 'precio base', 'duracion_proceso', 'unidad de duracion_proceso', 'fecha de recepcion de respuestas', 'fecha de apertura de respuesta', 'fecha de apertura efectiva', 'ciudad de la unidad de contratación', 'nombre de la unidad de contratación', 'proveedores invitados', 'proveedores con invitacion directa', 'visualizaciones del procedimiento', 'proveedores que manifestaron interes', 'respuestas al procedimiento', 'respuestas externas', 'conteo de respuestas a ofertas', 'proveedores unicos con respuestas', 'numero de lotes', 'estado del procedimiento', 'id estado del procedimiento', 'adjudicado', 'id adjudicacion', 'departamento proveedor', 'ciudad proveedor', 'fecha adjudicacion', 'valor total adjudicacion', 'nombre del adjudicador', 'nombre del proveedor adjudicado', 'estado de apertura del proceso', 'subtipo de contrato', 'estado resumen', 'Adicion']

## Eliminar columnas vacias y correción de nombre V.respuesta

In [27]:
# Contar valores nulos por columna
nulos = df.isnull().sum()
print(nulos)

nombre entidad                     0
nit entidad                        0
departamento                       0
ciudad                             0
localización                       0
                                  ..
nombre del proveedor adjudicado    8
estado de apertura del proceso     0
subtipo de contrato                0
estado resumen                     0
Adicion                            0
Length: 105, dtype: int64

In [28]:
# Porcentaje de valores nulos
porcentaje_nulos = df.isnull().mean() * 100
print(porcentaje_nulos)

nombre entidad                     0.000000
nit entidad                        0.000000
departamento                       0.000000
ciudad                             0.000000
localización                       0.000000
                                     ...
nombre del proveedor adjudicado    0.001346
estado de apertura del proceso     0.000000
subtipo de contrato                0.000000
estado resumen                     0.000000
Adicion                            0.000000
Length: 105, dtype: float64

In [29]:
# Umbral de eliminación (40% de valores nulos) de 0.1 a 0.40 son los mismos y solo el 20% ya son casi 120.000 columnas que tocaria eliminar
threshold = 0.4

# Identificar columnas con más del 40% de valores nulos
columnas_eliminadas = df.columns[df.isnull().mean() >= threshold]

# Imprimir columnas eliminadas
print("Columnas eliminadas por tener demasiados valores nulos:")
print(columnas_eliminadas)

# Eliminar las columnas del DataFrame
df = df[df.columns[df.isnull().mean() < threshold]]

Columnas eliminadas por tener demasiados valores nulos:
Index(['fecha de inicio de ejecucion', 'fecha de fin de ejecucion',
       'ultima actualizacion', 'fecha inicio liquidacion',
       'fecha fin liquidacion', 'fecha de notificación de prorrogación',
       'fecha de publicacion (manifestacion de interes)',
       'fecha de publicacion (fase borrador)',
       'fecha de recepcion de respuestas', 'fecha de apertura de respuesta',
       'fecha de apertura efectiva', 'fecha adjudicacion'],
      dtype='object')

In [30]:
df

,nombre entidad,nit entidad,departamento,ciudad,localización,orden,sector,rama,entidad centralizada,proceso de compra,...,id adjudicacion,departamento proveedor,ciudad proveedor,valor total adjudicacion,nombre del adjudicador,nombre del proveedor adjudicado,estado de apertura del proceso,subtipo de contrato,estado resumen,Adicion
0,UESVALLE,805018833,Valle del Cauca,Cali,Colombia Valle del Cauca Cali,Territorial,Salud y Protección Social,Ejecutivo,Centralizada,CO1.BDOS.3116030,...,No Adjudicado,Valle del Cauca,Florida,0,No Adjudicado,ALVARO JAVIER TIGREROS HURTADO,Abierto,No Definido,Adjudicado,1
1,SUBRED INTEGRADA DE SERVICIOS DE SALUD NORTE E...,900971006,Distrito Capital de Bogotá,No Definido,Colombia Bogotá No Definido,Territorial,Salud y Protección Social,Corporación Autónoma,Descentralizada,CO1.BDOS.2328666,...,No Adjudicado,Distrito Capital de Bogotá,Bogotá,0,No Adjudicado,Camilo Alonso Peralta,Abierto,No Definido,Adjudicado,1
2,SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR OCC...,900959048,Distrito Capital de Bogotá,No Definido,Colombia Bogotá No Definido,Territorial,Salud y Protección Social,Ejecutivo,Descentralizada,CO1.BDOS.7179284,...,No Adjudicado,Distrito Capital de Bogotá,No Definido,0,No Adjudicado,FABIOLA VANEGAS PORRAS,Abierto,No Definido,Adjudicado,1
3,UNIDAD PRESTADORA DE SALUD ATLANTICO,9013620904,Atlántico,Soledad,Colombia Atlántico Soledad,Territorial,Salud y Protección Social,Ejecutivo,Descentralizada,CO1.BDOS.5872894,...,CO1.AWD.1899212,Atlántico,Barranquilla,54000000,TATIANA CATALAN RIPOLL,ANDRES FELIPE MANJARRES MOLINA,Cerrado,No Definido,Adjudicado,1
4,SUBRED INTEGRADA DE SERVICIOS DE SALUD NORTE E...,900971006,Distrito Capital de Bogotá,No Definido,Colombia Bogotá No Definido,Territorial,Salud y Protección Social,Corporación Autónoma,Descentralizada,CO1.BDOS.414925,...,No Adjudicado,Distrito Capital de Bogotá,No Definido,0,No Adjudicado,Andrea Carolina Noches Buelvas,Abierto,No Definido,Adjudicado,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594512,RED SALUD CASANARE E.S.E. *,8440041972,Casanare,Yopal,Colombia Casanare Yopal,Territorial,Salud y Protección Social,Ejecutivo,Descentralizada,CO1.BDOS.5079011,...,No Adjudicado,Casanare,Villanueva,0,No Adjudicado,lida Marcela martinez,Abierto,No Definido,Adjudicado,0
594513,SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR OCC...,900959048,Distrito Capital de Bogotá,No Definido,Colombia Bogotá No Definido,Territorial,Salud y Protección Social,Ejecutivo,Descentralizada,CO1.BDOS.1053876,...,No Adjudicado,Cundinamarca,No Definido,0,No Adjudicado,YAMILY CIRO MARIN,Abierto,No Definido,Adjudicado,1
594514,ICBF REGIONAL NARIÑO,899999239,Nariño,No Definido,Colombia Nariño No Definido,Nacional,Salud y Protección Social,Ejecutivo,Centralizada,CO1.BDOS.6359883,...,No Adjudicado,Nariño,Pasto,0,No Adjudicado,HUMBERTO JAVIER PALACIOS ORDOÑEZ,Abierto,No Definido,Adjudicado,0
594515,SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR OCC...,900959048,Distrito Capital de Bogotá,No Definido,Colombia Bogotá No Definido,Territorial,Salud y Protección Social,Ejecutivo,Descentralizada,CO1.BDOS.7401171,...,No Adjudicado,Distrito Capital de Bogotá,Bogotá,0,No Adjudicado,WILLIAM DAVID ARREGOCES FERNANDEZ,Abierto,No Definido,Adjudicado,0
594516,SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR OCC...,900959048,Distrito Capital de Bogotá,No Definido,Colombia Bogotá No Definido,Territorial,Salud y Protección Social,Ejecutivo,Descentralizada,CO1.BDOS.1053876,...,No Adjudicado,Cundinamarca,No Definido,0,No Adjudicado,YAMILY CIRO MARIN,Abierto,No Definido,Adjudicado,1

## Remover duplicados y columnas que no funcionan desde el inicio

In [31]:
# Contar duplicados antes de eliminarlos
duplicates = len(df[df.duplicated()])
print(f'antes de remover: {duplicates}')

# Eliminar filas duplicadas
df = df.drop_duplicates()

# Contar duplicados después de eliminarlos
duplicates_after = len(df[df.duplicated()])
print(f'despues de remover: {duplicates_after}')

## Se removieron los duplicados antes de hacer el join con adicion por eso ahora no hay y la base paso de mas de 620.000 a lo de ahora

antes de remover: 0
despues de remover: 0

In [32]:
print(list(df.columns))

['nombre entidad', 'nit entidad', 'departamento', 'ciudad', 'localización', 'orden', 'sector', 'rama', 'entidad centralizada', 'proceso de compra', 'id contrato', 'estado contrato', 'codigo de categoria principal', 'tipo de contrato', 'modalidad de contratacion', 'justificacion modalidad de contratacion', 'fecha de firma', 'fecha de inicio del contrato', 'fecha de fin del contrato', 'condiciones de entrega', 'es grupo', 'es pyme', 'habilita pago adelantado', 'liquidación', 'obligación ambiental', 'obligaciones postconsumo', 'reversion', 'origen de los recursos', 'destino gasto', 'valor del contrato', 'valor de pago adelantado', 'valor facturado', 'valor pendiente de pago', 'valor pagado', 'valor amortizado', 'valor pendiente de amortizacion', 'valor pendiente de ejecucion', 'estado bpin', 'código bpin', 'anno bpin', 'saldo cdp', 'saldo vigencia', 'espostconflicto', 'dias adicionados', 'puntos del acuerdo', 'pilares del acuerdo', 'nombre representante legal', 'nacionalidad representante legal', 'presupuesto general de la nacion – pgn', 'sistema general de participaciones', 'sistema general de regalías', 'recursos propios (alcaldias_gobernaciones_resguardosindigenas)', 'recursos de credito', 'recursos propios', 'codigo entidad', 'duración del contrato', 'el contrato puede ser prorrogado', 'nombre ordenador del gasto', 'nombre supervisor', 'nombre ordenador de pago', 'id del proceso', 'id del portafolio', 'fase', 'fecha de publicacion del proceso', 'fecha de ultima publicación', 'fecha de publicacion (fase seleccion)', 'precio base', 'duracion_proceso', 'unidad de duracion_proceso', 'ciudad de la unidad de contratación', 'nombre de la unidad de contratación', 'proveedores invitados', 'proveedores con invitacion directa', 'visualizaciones del procedimiento', 'proveedores que manifestaron interes', 'respuestas al procedimiento', 'respuestas externas', 'conteo de respuestas a ofertas', 'proveedores unicos con respuestas', 'numero de lotes', 'estado del procedimiento', 'id estado del procedimiento', 'adjudicado', 'id adjudicacion', 'departamento proveedor', 'ciudad proveedor', 'valor total adjudicacion', 'nombre del adjudicador', 'nombre del proveedor adjudicado', 'estado de apertura del proceso', 'subtipo de contrato', 'estado resumen', 'Adicion']

### eliminacion de variables no necesarias desde el inicio

In [33]:
df = df.drop('localización', axis=1)
df = df.drop('id contrato', axis=1)
df = df.drop('proceso de compra', axis=1)
df = df.drop('id del proceso', axis=1)
df = df.drop('id del portafolio', axis=1)
df = df.drop('sector', axis=1)

In [34]:
# Definir el umbral
threshold = 0.99  # 99% de valores iguales

# Identificar columnas con 99% o más valores iguales
columnas_iguales = [col for col in df.columns if df[col].value_counts(normalize=True, dropna=False).values[0] >= threshold]

# Imprimir columnas con valores repetidos en 99% o más de los casos
print("Columnas con 99% o más de valores iguales:")
print(columnas_iguales)

df = df.drop(columns=columnas_iguales)

Columnas con 99% o más de valores iguales:
['proveedores invitados', 'proveedores con invitacion directa', 'proveedores que manifestaron interes', 'respuestas externas', 'conteo de respuestas a ofertas', 'estado del procedimiento', 'subtipo de contrato', 'estado resumen']

### Creacion de duracion de contratos e eliminacion de fechas

In [35]:
# Asegurarse de que las columnas de fechas están en formato datetime
df['fecha de inicio del contrato'] = pd.to_datetime(df['fecha de inicio del contrato'], errors='coerce')
df['fecha de fin del contrato'] = pd.to_datetime(df['fecha de fin del contrato'], errors='coerce')

# Calcular la duración en días y crear la nueva columna
df['tiempo duracion (dias)'] = (df['fecha de fin del contrato'] - df['fecha de inicio del contrato']).dt.days



# Verificar el resultado
print(df[['fecha de inicio del contrato', 'fecha de fin del contrato', 'tiempo duracion (dias)']])

df = df.drop('fecha de inicio del contrato', axis=1)
df = df.drop('fecha de fin del contrato', axis=1)
df = df.drop('duración del contrato', axis=1)

       fecha de inicio del contrato fecha de fin del contrato  \
0                               NaT                       NaT
1                        2021-10-28                2022-01-31
2                        2024-12-14                2025-04-09
3                        2024-04-20                2024-09-30
4                        2018-05-02                2018-07-31
...                             ...                       ...
594512                   2023-10-23                2023-11-22
594513                   2020-02-01                2021-01-31
594514                   2024-07-09                2024-12-31
594515                   2025-02-01                2025-05-31
594516                   2020-02-01                2020-04-03

        tiempo duracion (dias)
0                          NaN
1                         95.0
2                        116.0
3                        163.0
4                         90.0
...                        ...
594512                    30.0
594513                   365.0
594514                   175.0
594515                   119.0
594516                    62.0

[594517 rows x 3 columns]

In [36]:
df

,nombre entidad,nit entidad,departamento,ciudad,orden,rama,entidad centralizada,estado contrato,codigo de categoria principal,tipo de contrato,...,adjudicado,id adjudicacion,departamento proveedor,ciudad proveedor,valor total adjudicacion,nombre del adjudicador,nombre del proveedor adjudicado,estado de apertura del proceso,Adicion,tiempo duracion (dias)
0,UESVALLE,805018833,Valle del Cauca,Cali,Territorial,Ejecutivo,Centralizada,Cerrado,V1.80111701,NaN,...,No,No Adjudicado,Valle del Cauca,Florida,0,No Adjudicado,ALVARO JAVIER TIGREROS HURTADO,Abierto,1,NaN
1,SUBRED INTEGRADA DE SERVICIOS DE SALUD NORTE E...,900971006,Distrito Capital de Bogotá,No Definido,Territorial,Corporación Autónoma,Descentralizada,Modificado,V1.85101600,Decreto 092 de 2017,...,No,No Adjudicado,Distrito Capital de Bogotá,Bogotá,0,No Adjudicado,Camilo Alonso Peralta,Abierto,1,95.0
2,SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR OCC...,900959048,Distrito Capital de Bogotá,No Definido,Territorial,Ejecutivo,Descentralizada,Modificado,V1.85101604,Prestación de servicios,...,No,No Adjudicado,Distrito Capital de Bogotá,No Definido,0,No Adjudicado,FABIOLA VANEGAS PORRAS,Abierto,1,116.0
3,UNIDAD PRESTADORA DE SALUD ATLANTICO,9013620904,Atlántico,Soledad,Territorial,Ejecutivo,Descentralizada,Modificado,V1.80161801,Prestación de servicios,...,Si,CO1.AWD.1899212,Atlántico,Barranquilla,54000000,TATIANA CATALAN RIPOLL,ANDRES FELIPE MANJARRES MOLINA,Cerrado,1,163.0
4,SUBRED INTEGRADA DE SERVICIOS DE SALUD NORTE E...,900971006,Distrito Capital de Bogotá,No Definido,Territorial,Corporación Autónoma,Descentralizada,En aprobación,V1.85101600,Prestación de servicios,...,No,No Adjudicado,Distrito Capital de Bogotá,No Definido,0,No Adjudicado,Andrea Carolina Noches Buelvas,Abierto,0,90.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594512,RED SALUD CASANARE E.S.E. *,8440041972,Casanare,Yopal,Territorial,Ejecutivo,Descentralizada,En ejecución,V1.80111701,Prestación de servicios,...,No,No Adjudicado,Casanare,Villanueva,0,No Adjudicado,lida Marcela martinez,Abierto,0,30.0
594513,SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR OCC...,900959048,Distrito Capital de Bogotá,No Definido,Territorial,Ejecutivo,Descentralizada,Modificado,V1.80111600,Prestación de servicios,...,No,No Adjudicado,Cundinamarca,No Definido,0,No Adjudicado,YAMILY CIRO MARIN,Abierto,1,365.0
594514,ICBF REGIONAL NARIÑO,899999239,Nariño,No Definido,Nacional,Ejecutivo,Centralizada,En ejecución,V1.80111600,Prestación de servicios,...,No,No Adjudicado,Nariño,Pasto,0,No Adjudicado,HUMBERTO JAVIER PALACIOS ORDOÑEZ,Abierto,0,175.0
594515,SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR OCC...,900959048,Distrito Capital de Bogotá,No Definido,Territorial,Ejecutivo,Descentralizada,En ejecución,V1.85101604,Prestación de servicios,...,No,No Adjudicado,Distrito Capital de Bogotá,Bogotá,0,No Adjudicado,WILLIAM DAVID ARREGOCES FERNANDEZ,Abierto,0,119.0
594516,SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR OCC...,900959048,Distrito Capital de Bogotá,No Definido,Territorial,Ejecutivo,Descentralizada,terminado,V1.80111600,Prestación de servicios,...,No,No Adjudicado,Cundinamarca,No Definido,0,No Adjudicado,YAMILY CIRO MARIN,Abierto,1,62.0

In [37]:
# número de valores perdidos
missing_values = df.isnull().sum().sum()
print(f'Number of Missing Values: {missing_values}')

Number of Missing Values: 1532591

In [38]:
# Contar valores nulos por columna
missing_values_per_column = df.isnull().sum()

# Filtrar solo las columnas con valores nulos
missing_values_per_column = missing_values_per_column[missing_values_per_column > 0]

# Ordenar en orden descendente
missing_values_per_column = missing_values_per_column.sort_values(ascending=False)

# Imprimir el resultado
print(missing_values_per_column)

tiempo duracion (dias)                                            85243
fecha de firma                                                    83420
nombre ordenador del gasto                                        30981
nombre supervisor                                                 30981
el contrato puede ser prorrogado                                  30981
nombre ordenador de pago                                          30981
condiciones de entrega                                            30465
obligaciones postconsumo                                          30465
justificacion modalidad de contratacion                           30465
liquidación                                                       30465
obligación ambiental                                              30465
valor del contrato                                                30465
reversion                                                         30465
origen de los recursos                                            30465
es grupo                                                          30465
es pyme                                                           30465
habilita pago adelantado                                          30465
modalidad de contratacion                                         30465
tipo de contrato                                                  30465
presupuesto general de la nacion – pgn                            30465
valor pendiente de pago                                           30465
valor de pago adelantado                                          30465
valor facturado                                                   30465
destino gasto                                                     30465
valor pagado                                                      30465
valor pendiente de amortizacion                                   30465
valor amortizado                                                  30465
saldo vigencia                                                    30465
espostconflicto                                                   30465
dias adicionados                                                  30465
valor pendiente de ejecucion                                      30465
estado bpin                                                       30465
código bpin                                                       30465
anno bpin                                                         30465
saldo cdp                                                         30465
recursos propios                                                  30465
nacionalidad representante legal                                  30465
nombre representante legal                                        30465
pilares del acuerdo                                               30465
puntos del acuerdo                                                30465
recursos de credito                                               30465
sistema general de participaciones                                30465
sistema general de regalías                                       30465
recursos propios (alcaldias_gobernaciones_resguardosindigenas)    30465
codigo entidad                                                    30465
fecha de publicacion (fase seleccion)                             16086
fecha de ultima publicación                                       11852
fecha de publicacion del proceso                                  11852
estado contrato                                                   11785
fase                                                                286
nombre del proveedor adjudicado                                       8
dtype: int64

In [39]:
# Contar valores nulos por columna
missing_values_per_column = df.isnull().sum()

# Filtrar solo las columnas con valores nulos
columns_with_nans = missing_values_per_column[missing_values_per_column > 0].index

# Eliminar filas con valores nulos en estas columnas
df = df.dropna(subset=columns_with_nans)

# Imprimir confirmación
print(f"Se eliminaron las filas con valores nulos en las siguientes columnas:\n{list(columns_with_nans)}")

Se eliminaron las filas con valores nulos en las siguientes columnas:
['estado contrato', 'tipo de contrato', 'modalidad de contratacion', 'justificacion modalidad de contratacion', 'fecha de firma', 'condiciones de entrega', 'es grupo', 'es pyme', 'habilita pago adelantado', 'liquidación', 'obligación ambiental', 'obligaciones postconsumo', 'reversion', 'origen de los recursos', 'destino gasto', 'valor del contrato', 'valor de pago adelantado', 'valor facturado', 'valor pendiente de pago', 'valor pagado', 'valor amortizado', 'valor pendiente de amortizacion', 'valor pendiente de ejecucion', 'estado bpin', 'código bpin', 'anno bpin', 'saldo cdp', 'saldo vigencia', 'espostconflicto', 'dias adicionados', 'puntos del acuerdo', 'pilares del acuerdo', 'nombre representante legal', 'nacionalidad representante legal', 'presupuesto general de la nacion – pgn', 'sistema general de participaciones', 'sistema general de regalías', 'recursos propios (alcaldias_gobernaciones_resguardosindigenas)', 'recursos de credito', 'recursos propios', 'codigo entidad', 'el contrato puede ser prorrogado', 'nombre ordenador del gasto', 'nombre supervisor', 'nombre ordenador de pago', 'fase', 'fecha de publicacion del proceso', 'fecha de ultima publicación', 'fecha de publicacion (fase seleccion)', 'nombre del proveedor adjudicado', 'tiempo duracion (dias)']

In [40]:
df = df.reset_index(drop=True)
df

,nombre entidad,nit entidad,departamento,ciudad,orden,rama,entidad centralizada,estado contrato,codigo de categoria principal,tipo de contrato,...,adjudicado,id adjudicacion,departamento proveedor,ciudad proveedor,valor total adjudicacion,nombre del adjudicador,nombre del proveedor adjudicado,estado de apertura del proceso,Adicion,tiempo duracion (dias)
0,SUBRED INTEGRADA DE SERVICIOS DE SALUD NORTE E...,900971006,Distrito Capital de Bogotá,No Definido,Territorial,Corporación Autónoma,Descentralizada,Modificado,V1.85101600,Decreto 092 de 2017,...,No,No Adjudicado,Distrito Capital de Bogotá,Bogotá,0,No Adjudicado,Camilo Alonso Peralta,Abierto,1,95.0
1,SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR OCC...,900959048,Distrito Capital de Bogotá,No Definido,Territorial,Ejecutivo,Descentralizada,Modificado,V1.85101604,Prestación de servicios,...,No,No Adjudicado,Distrito Capital de Bogotá,No Definido,0,No Adjudicado,FABIOLA VANEGAS PORRAS,Abierto,1,116.0
2,UNIDAD PRESTADORA DE SALUD ATLANTICO,9013620904,Atlántico,Soledad,Territorial,Ejecutivo,Descentralizada,Modificado,V1.80161801,Prestación de servicios,...,Si,CO1.AWD.1899212,Atlántico,Barranquilla,54000000,TATIANA CATALAN RIPOLL,ANDRES FELIPE MANJARRES MOLINA,Cerrado,1,163.0
3,EMPRESA SOCIAL DEL ESTADO DEL DEPARTAMENTO DEL...,822006595,Meta,Villavicencio,Territorial,Ejecutivo,Centralizada,En ejecución,V1.85101600,Prestación de servicios,...,No,No Adjudicado,Meta,Guamal,0,No Adjudicado,DERLY JOHANA VIRGUEZ PEÑA,Abierto,0,38.0
4,SUBRED INTEGRADA DE SERVICIO DE SALUD CENTRO O...,900959051,Distrito Capital de Bogotá,No Definido,Territorial,Ejecutivo,Descentralizada,En ejecución,V1.80111600,Prestación de servicios,...,No,No Adjudicado,Distrito Capital de Bogotá,Bogotá,0,No Adjudicado,HENRRY DANIEL DELGADO RODRIGUEZ,Abierto,1,48.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487207,RED SALUD CASANARE E.S.E. *,8440041972,Casanare,Yopal,Territorial,Ejecutivo,Descentralizada,En ejecución,V1.80111701,Prestación de servicios,...,No,No Adjudicado,Casanare,Villanueva,0,No Adjudicado,lida Marcela martinez,Abierto,0,30.0
487208,SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR OCC...,900959048,Distrito Capital de Bogotá,No Definido,Territorial,Ejecutivo,Descentralizada,Modificado,V1.80111600,Prestación de servicios,...,No,No Adjudicado,Cundinamarca,No Definido,0,No Adjudicado,YAMILY CIRO MARIN,Abierto,1,365.0
487209,ICBF REGIONAL NARIÑO,899999239,Nariño,No Definido,Nacional,Ejecutivo,Centralizada,En ejecución,V1.80111600,Prestación de servicios,...,No,No Adjudicado,Nariño,Pasto,0,No Adjudicado,HUMBERTO JAVIER PALACIOS ORDOÑEZ,Abierto,0,175.0
487210,SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR OCC...,900959048,Distrito Capital de Bogotá,No Definido,Territorial,Ejecutivo,Descentralizada,En ejecución,V1.85101604,Prestación de servicios,...,No,No Adjudicado,Distrito Capital de Bogotá,Bogotá,0,No Adjudicado,WILLIAM DAVID ARREGOCES FERNANDEZ,Abierto,0,119.0
487211,SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR OCC...,900959048,Distrito Capital de Bogotá,No Definido,Territorial,Ejecutivo,Descentralizada,terminado,V1.80111600,Prestación de servicios,...,No,No Adjudicado,Cundinamarca,No Definido,0,No Adjudicado,YAMILY CIRO MARIN,Abierto,1,62.0

In [41]:
# Si el departamento es "Distrito Capital de Bogotá" y el orden es "Territorial", poner "Bogotá"
df.loc[(df['departamento'] == 'Distrito Capital de Bogotá') & (df['orden'] == 'Territorial'), 'ciudad'] = 'Bogotá'

# Si el departamento es "Distrito Capital de Bogotá" y el orden es "Nacional", poner "Bogotá_Nacional"
df.loc[(df['departamento'] == 'Distrito Capital de Bogotá') & (df['orden'] == 'Nacional'), 'ciudad'] = 'Bogotá_Nacional'

# Verificar los cambios
df['ciudad'].value_counts().head(10)

ciudad
Bogotá             221006
Bogotá_Nacional     29042
No Definido         28156
Cali                23715
Santa Marta         15907
Cartagena            9068
Manizales            8340
Villavicencio        7621
Soacha               5982
Bucaramanga          5889
Name: count, dtype: int64

## Analisis de tipos de datos y variables que quedan para analisis

In [42]:
columnas_fecha = ['fecha de firma', 'fecha de ultima publicación', 'fecha de publicacion (fase seleccion)']

for col in columnas_fecha:
    df[col] = pd.to_datetime(df[col], errors='coerce', dayfirst=True)  # Asume día/mes/año

C:\Users\asus\AppData\Local\Temp\ipykernel_4428\2995022876.py:4: UserWarning: Parsing dates in %m/%d/%Y format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors='coerce', dayfirst=True)  # Asume día/mes/año
C:\Users\asus\AppData\Local\Temp\ipykernel_4428\2995022876.py:4: UserWarning: Parsing dates in %m/%d/%Y format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors='coerce', dayfirst=True)  # Asume día/mes/año
C:\Users\asus\AppData\Local\Temp\ipykernel_4428\2995022876.py:4: UserWarning: Parsing dates in %m/%d/%Y format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors='coerce', dayfirst=True)  # Asume día/mes/año

In [43]:
# Verificar los tipos de datos de las columnas
df.dtypes

nombre entidad                      object
nit entidad                          int64
departamento                        object
ciudad                              object
orden                               object
                                    ...
nombre del adjudicador              object
nombre del proveedor adjudicado     object
estado de apertura del proceso      object
Adicion                              int64
tiempo duracion (dias)             float64
Length: 77, dtype: object

In [44]:
types = df.dtypes.value_counts()
print('Data Types and Frequency in Dataset:')
print(types)

Data Types and Frequency in Dataset:
object            45
float64           19
int64             10
datetime64[ns]     3
Name: count, dtype: int64

In [45]:
print(list(df.columns))

['nombre entidad', 'nit entidad', 'departamento', 'ciudad', 'orden', 'rama', 'entidad centralizada', 'estado contrato', 'codigo de categoria principal', 'tipo de contrato', 'modalidad de contratacion', 'justificacion modalidad de contratacion', 'fecha de firma', 'condiciones de entrega', 'es grupo', 'es pyme', 'habilita pago adelantado', 'liquidación', 'obligación ambiental', 'obligaciones postconsumo', 'reversion', 'origen de los recursos', 'destino gasto', 'valor del contrato', 'valor de pago adelantado', 'valor facturado', 'valor pendiente de pago', 'valor pagado', 'valor amortizado', 'valor pendiente de amortizacion', 'valor pendiente de ejecucion', 'estado bpin', 'código bpin', 'anno bpin', 'saldo cdp', 'saldo vigencia', 'espostconflicto', 'dias adicionados', 'puntos del acuerdo', 'pilares del acuerdo', 'nombre representante legal', 'nacionalidad representante legal', 'presupuesto general de la nacion – pgn', 'sistema general de participaciones', 'sistema general de regalías', 'recursos propios (alcaldias_gobernaciones_resguardosindigenas)', 'recursos de credito', 'recursos propios', 'codigo entidad', 'el contrato puede ser prorrogado', 'nombre ordenador del gasto', 'nombre supervisor', 'nombre ordenador de pago', 'fase', 'fecha de publicacion del proceso', 'fecha de ultima publicación', 'fecha de publicacion (fase seleccion)', 'precio base', 'duracion_proceso', 'unidad de duracion_proceso', 'ciudad de la unidad de contratación', 'nombre de la unidad de contratación', 'visualizaciones del procedimiento', 'respuestas al procedimiento', 'proveedores unicos con respuestas', 'numero de lotes', 'id estado del procedimiento', 'adjudicado', 'id adjudicacion', 'departamento proveedor', 'ciudad proveedor', 'valor total adjudicacion', 'nombre del adjudicador', 'nombre del proveedor adjudicado', 'estado de apertura del proceso', 'Adicion', 'tiempo duracion (dias)']

In [46]:
# 'fecha de publicacion del proceso' y 'fecha de ultima publicación' son exacatemnte iguales
df = df.drop('fecha de publicacion del proceso', axis=1)

In [47]:
# Seleccionar las dos primeras columnas de interés
columnas_interes = ['fecha de ultima publicación', 'fecha de publicacion (fase seleccion)']

# Verificar si las columnas existen
columnas_existentes = [col for col in columnas_interes if col in df.columns]

# Contar cuántas filas son diferentes entre estas dos columnas
if len(columnas_existentes) == 2:
    filas_diferentes = (df[columnas_existentes[0]] != df[columnas_existentes[1]]).sum()
    print(f"Número de filas donde las fechas son diferentes: {filas_diferentes}")
else:
    print("Las columnas necesarias no existen en el DataFrame.")

Número de filas donde las fechas son diferentes: 11993

In [48]:
# Definir función para convertir cualquier unidad a días
def convertir_a_dias(valor, unidad):
    if pd.isnull(valor) or pd.isnull(unidad):  # Manejar valores nulos
        return None
    unidad = unidad.lower().strip()  # Convertir a minúsculas y eliminar espacios
    
    if unidad in ['año(s)', 'años']:  # Conversión de años a días
        return valor * 365
    elif unidad in ['mes(es)', 'mes']:  # Conversión de meses a días
        return valor * 30
    elif unidad in ['semana(s)', 'semanas']:  # Conversión de semanas a días
        return valor * 7
    elif unidad in ['día(s)', 'días']:  # Ya está en días
        return valor
    elif unidad in ['hora(s)', 'horas']:  # Conversión de horas a días
        return valor / 24
    else:
        return None  # Otras unidades desconocidas

# Aplicar la conversión a toda la columna
df['duracion_proceso_dias'] = df.apply(lambda row: convertir_a_dias(row['duracion_proceso'], row['unidad de duracion_proceso']), axis=1)

In [49]:
df=df.drop("duracion_proceso",axis=1)
df=df.drop("unidad de duracion_proceso",axis=1)

In [53]:
ejemplo=df.head(10000)
ejemplo.to_excel("revisionlimpieza.xlsx",index=False)

ModuleNotFoundError: No module named 'openpyxl'

In [60]:
def clean_categorical_variables(df, city_threshold=0.0001, general_threshold=0.01):
    df_copy = df.copy()
    for col in df_copy.select_dtypes(include=['object', 'category']):
        if col == 'ciudad':
            threshold = city_threshold
        else:
            threshold = general_threshold
        
        counts = df_copy[col].value_counts(normalize=True)
        low_freq_categories = counts[counts < threshold].index
        df_copy[col] = df_copy[col].replace(low_freq_categories, "Otra")
    
    return df_copy

df = clean_categorical_variables(df)

In [61]:
df

,nombre entidad,nit entidad,departamento,ciudad,orden,rama,entidad centralizada,estado contrato,codigo de categoria principal,tipo de contrato,...,adjudicado,id adjudicacion,departamento proveedor,ciudad proveedor,valor total adjudicacion,nombre del adjudicador,nombre del proveedor adjudicado,estado de apertura del proceso,Adicion,tiempo duracion (dias)
0,SUBRED INTEGRADA DE SERVICIOS DE SALUD NORTE E...,900971006,Distrito Capital de Bogotá,Bogotá,Territorial,Corporación Autónoma,Descentralizada,Modificado,V1.85101600,Decreto 092 de 2017,...,No,No Adjudicado,Distrito Capital de Bogotá,Bogotá,0,No Adjudicado,Otra,Abierto,1,95.0
1,SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR OCC...,900959048,Distrito Capital de Bogotá,Bogotá,Territorial,Ejecutivo,Descentralizada,Modificado,V1.85101604,Prestación de servicios,...,No,No Adjudicado,Distrito Capital de Bogotá,No Definido,0,No Adjudicado,Otra,Abierto,1,116.0
2,Otra,9013620904,Atlántico,Soledad,Territorial,Ejecutivo,Descentralizada,Modificado,Otra,Prestación de servicios,...,Si,Otra,Atlántico,Barranquilla,54000000,Otra,Otra,Cerrado,1,163.0
3,Otra,822006595,Meta,Villavicencio,Territorial,Ejecutivo,Centralizada,En ejecución,V1.85101600,Prestación de servicios,...,No,No Adjudicado,Meta,Otra,0,No Adjudicado,Otra,Abierto,0,38.0
4,SUBRED INTEGRADA DE SERVICIO DE SALUD CENTRO O...,900959051,Distrito Capital de Bogotá,Bogotá,Territorial,Ejecutivo,Descentralizada,En ejecución,V1.80111600,Prestación de servicios,...,No,No Adjudicado,Distrito Capital de Bogotá,Bogotá,0,No Adjudicado,Otra,Abierto,1,48.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487207,Otra,8440041972,Casanare,Yopal,Territorial,Ejecutivo,Descentralizada,En ejecución,V1.80111701,Prestación de servicios,...,No,No Adjudicado,Casanare,Otra,0,No Adjudicado,Otra,Abierto,0,30.0
487208,SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR OCC...,900959048,Distrito Capital de Bogotá,Bogotá,Territorial,Ejecutivo,Descentralizada,Modificado,V1.80111600,Prestación de servicios,...,No,No Adjudicado,Cundinamarca,No Definido,0,No Adjudicado,Otra,Abierto,1,365.0
487209,Otra,899999239,Nariño,No Definido,Nacional,Ejecutivo,Centralizada,En ejecución,V1.80111600,Prestación de servicios,...,No,No Adjudicado,Nariño,Otra,0,No Adjudicado,Otra,Abierto,0,175.0
487210,SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR OCC...,900959048,Distrito Capital de Bogotá,Bogotá,Territorial,Ejecutivo,Descentralizada,En ejecución,V1.85101604,Prestación de servicios,...,No,No Adjudicado,Distrito Capital de Bogotá,Bogotá,0,No Adjudicado,Otra,Abierto,0,119.0
487211,SUBRED INTEGRADA DE SERVICIOS DE SALUD SUR OCC...,900959048,Distrito Capital de Bogotá,Bogotá,Territorial,Ejecutivo,Descentralizada,terminado,V1.80111600,Prestación de servicios,...,No,No Adjudicado,Cundinamarca,No Definido,0,No Adjudicado,Otra,Abierto,1,62.0

In [63]:
df.to_csv("base con categorias reducidas2.csv",index=False)